# Generated by Django 3.0.2 on 2022-01-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200420_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtd_estoque',
            new_name='qtd',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
